[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "setuptools_scm>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/preppipe/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"
