name: autotest

on: [push, pull_request, workflow_dispatch]

jobs:
  autotest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: test
        run: python3 -m unittest
        shell: bash

