name: "Build raw asset zip"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-asset-zip:
    name: "Build asset zip"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: create source assets zip
        shell: bash
        run: |
          mkdir -p dist
          7z a -tzip -mx=9 dist/builtin-assets.zip assets/*
      - name: "Upload zip"
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "builtin-assets"
          name: "内置资源 (Builtin assets)"
          prerelease: true
          files: |
            dist/builtin-assets.zip
