name: preppipe-test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - name: fetch tags
        run: git fetch --prune --unshallow --tags
      - name: environment dump
        run: |
          python3 --version
          git --version
          git describe --tags
      - name: install dependencies
        run: |
          sudo apt-get install -y ffmpeg
          sudo python3 -m pip install --upgrade build twine
      - name: build
        run: python3 -m build
      - name: install
        run: sudo python3 -m pip install dist/*.whl
      - name: test
        run: python3 -m unittest
      - name: publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
