name: preppipe-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install ffmpeg
          sudo python3 -m pip install --upgrade build
      - name: build
        run: python3 -m build
      - name: install
        run: sudo python3 -m pip install dist/*.whl
      - name: test
        run: python3 -m unittest

