name: testpypi-publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/project/preppipe/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: "Download release"
        id: download_main
        uses: robinraju/release-downloader@v1.10
        with:
          tag: "latest-main"
          fileName: "*.whl"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
